# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{blundersaur}
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jeremy Stephens"]
  s.date = %q{2011-05-20}
  s.description = %q{A library of Ruby methods to simulate data entry mistakes}
  s.email = %q{viking@pillageandplunder.net}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "blundersaur.gemspec",
    "lib/blundersaur.rb",
    "lib/blundersaur/extensions.rb",
    "lib/blundersaur/extensions/string.rb",
    "lib/blundersaur/keyboards.rb",
    "lib/blundersaur/keyboards/qwerty.rb",
    "test.watchr",
    "test/blundersaur/extensions/test_string.rb",
    "test/blundersaur/keyboards/test_qwerty.rb",
    "test/blundersaur/test_extensions.rb",
    "test/helper.rb",
    "test/test_blundersaur.rb"
  ]
  s.homepage = %q{https://github.com/viking/blundersaur}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.7.2}
  s.summary = %q{A library of Ruby methods to simulate data entry mistakes}
  s.test_files = [
    "test/blundersaur/extensions/test_string.rb",
    "test/blundersaur/keyboards/test_qwerty.rb",
    "test/blundersaur/test_extensions.rb",
    "test/helper.rb",
    "test/test_blundersaur.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

