# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{blundersaur}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jeremy Stephens"]
  s.date = %q{2010-02-03}
  s.description = %q{A library of Ruby methods to simulate data entry mistakes}
  s.email = %q{viking415@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "lib/blundersaur.rb",
     "lib/blundersaur/extensions.rb",
     "lib/blundersaur/extensions/string.rb",
     "lib/blundersaur/keyboards.rb",
     "lib/blundersaur/keyboards/qwerty.rb",
     "test.watchr",
     "test/blundersaur/extensions/test_string.rb",
     "test/blundersaur/keyboards/test_qwerty.rb",
     "test/blundersaur/test_extensions.rb",
     "test/helper.rb",
     "test/test_blundersaur.rb"
  ]
  s.homepage = %q{http://github.com/viking/blundersaur}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{A library of Ruby methods to simulate data entry mistakes}
  s.test_files = [
    "test/blundersaur/test_extensions.rb",
     "test/blundersaur/extensions/test_string.rb",
     "test/blundersaur/keyboards/test_qwerty.rb",
     "test/helper.rb",
     "test/test_blundersaur.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

